### ISSUE TITLE
Misc readme errors

### ISSUE THREAD

**Issue by spenser6131** [learn-co-curriculum/fewpjs-iterators-fndcl-fnexpr-map-lab#5]
> Because for and for...of are general functions that can be used to **_do lots of things another programmer_** won't be sure if the inner workings return values are important or not.

should be "do lots of things, another programmer"

<br><br>
The final sentence of the section "map() With an Arrow Function" reads:
> For the rest of of these examples, we'll use the arrow function.

But this is not the case, as regular functions are used instead of arrow functions for the remainder of the lab.

**Comment by lizbur10** [comment]
Hi there! Thanks so much for submitting this issue. The materials have been updated and your errors have been addressed, so I am closing this issue. 

Thanks for contributing to the Flatiron curriculum 💙
